//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreewayIsuzu.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VincontrolContainer : DbContext
    {
        public VincontrolContainer()
            : base("name=VincontrolContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appraisal> Appraisals { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
    }
}
